export const states = [
  "Tense",
  "Angry",
  "Worn Out",
  "Unhappy",
  "Proud",
  "Lively",
  "Confused",
  "Sad",
  "Active",
  "On-edge",
  "Grouchy",
  "Ashamed",
  "Energetic",
  "Hopeless",
  "Uneasy",
  "Restless",
  "Unable to concentrate",
  "Fatigued",
  "Competent",
  "Annoyed",
  "Discouraged",
  "Resentful",
  "Nervous",
  "Miserable",
  "Confident",
  "Bitter",
  "Exhausted",
  "Anxious",
  "Helpless",
  "Weary",
  "Satisfied",
  "Bewildered",
  "Furious",
  "Full of Pep",
  "Worthless",
  "Forgetful",
  "Vigorous",
  "Uncertain about things",
  "Bushed",
  "Embarrassed",
];

[
  { scale: "Tension", item: "Tense" },
  { scale: "Anger", item: "Angry" },
  { scale: "Fatigue", item: "Fatigued" },
  { scale: "Depression", item: "Depressed" },
  { scale: "Esteem-related Affect", item: "Proud" },
  { scale: "Vigour", item: "Vigorous" },
  { scale: "Confusion", item: "Confused" },
  { scale: "Vigour", item: "Active" },
  { scale: "Tension", item: "On Edge" },
  { scale: "Anger", item: "Grouchy" },
  { scale: "Esteem-related Affect", item: "Ashamed" },
  { scale: "Vigour", item: "Energetic" },
  { scale: "Depression", item: "Hopeless" },
  { scale: "Tension", item: "Uneasy" },
  { scale: "Tension", item: "Restless" },
  { scale: "Confusion", item: "Concentration Lapses" },
  { scale: "Fatigue", item: "Fatigued" },
  { scale: "Esteem-related Affect", item: "Competent" },
  { scale: "Anger", item: "Annoyed" },
  { scale: "Depression", item: "Discouraged" },
  { scale: "Anger", item: "Resentful" },
  { scale: "Tension", item: "Nervous" },
  { scale: "Depression", item: "Miserable" },
  { scale: "Esteem-related Affect", item: "Confident" },
  { scale: "Anger", item: "Bitter" },
  { scale: "Fatigue", item: "Exhausted" },
  { scale: "Tension", item: "Anxious" },
  { scale: "Depression", item: "Helpless" },
  { scale: "Fatigue", item: "Weary" },
  { scale: "Esteem-related Affect", item: "Satisfied" },
  { scale: "Confusion", item: "Bewildered" },
  { scale: "Anger", item: "Furious" },
  { scale: "Vigour", item: "Full of Pep" },
  { scale: "Depression", item: "Worthless" },
  { scale: "Confusion", item: "Forgetful" },
  { scale: "Vigour", item: "Vigorous" },
  { scale: "Confusion", item: "Uncertain" },
  { scale: "Fatigue", item: "Bushed" },
  { scale: "Esteem-related Affect", item: "Embarrassed" },
];

export const moodStates = [
  {
    dimension: "Tension",
    name: "Tense",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Anger",
    name: "Angry",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Fatigue",
    name: "Worn Out",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Unhappy",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Esteem-related Affect",
    name: "Proud",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Vigour",
    name: "Lively",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Confusion",
    name: "Confused",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Sad",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Vigour",
    name: "Active",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Tension",
    name: "On-edge",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Anger",
    name: "Grouchy",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Esteem-related Affect",
    name: "Ashamed",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Vigour",
    name: "Energetic",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Hopeless",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Tension",
    name: "Uneasy",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Tension",
    name: "Restless",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Confusion",
    name: "Can't concentrate",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Fatigue",
    name: "Fatigued",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Esteem-related Affect",
    name: "Competent",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Anger",
    name: "Annoyed",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Discouraged",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Anger",
    name: "Resentful",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Tension",
    name: "Nervous",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Miserable",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Esteem-related Affect",
    name: "Confident",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Anger",
    name: "Bitter",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Fatigue",
    name: "Exhausted",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Tension",
    name: "Anxious",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Helpless",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Fatigue",
    name: "Weary",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Esteem-related Affect",
    name: "Satisfied",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Confusion",
    name: "Bewildered",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Anger",
    name: "Furious",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Vigour",
    name: "Full of Pep",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Depression",
    name: "Worthless",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Confusion",
    name: "Forgetful",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Vigour",
    name: "Vigorous",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Confusion",
    name: "Uncertain about things",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Fatigue",
    name: "Bushed",
    reverseScored: false,
    scaleLength: 5,
  },
  {
    dimension: "Esteem-related Affect",
    name: "Embarrassed",
    reverseScored: false,
    scaleLength: 5,
  },
];
